/potential_function_node_0:
  ros__parameters:
    current_robot_id: 0
    current_robot_name: "tb_0_0"
    number_of_obstacles: 0
    radius_of_robots: 1.0
    radius_outer: 20.0
    limit_distance_for_robots: 5.0
    K_gain: 50.0
    Kp_v: 0.1
    Ki_v: 0.0
    Kd_v: 0.0
    Kp_w: 0.8
    Ki_w: 0.05
    Kd_w: 0.0
    threshold_for_linear_velocity: 0.1
    threshold_for_angular_velocity: 0.01
    anti_windup_for_linear_velocity: 0.2
    anti_windup_for_angular_velocity: 0.7

/potential_function_node_1:
  ros__parameters:
    current_robot_id: 1
    current_robot_name: "tb_1_0"
    number_of_obstacles: 0
    radius_of_robots: 1.0
    radius_outer: 20.0
    limit_distance_for_robots: 5.0
    K_gain: 50.0
    Kp_v: 0.1
    Ki_v: 0.0
    Kd_v: 0.0
    Kp_w: 0.8
    Ki_w: 0.05
    Kd_w: 0.0
    threshold_for_linear_velocity: 0.1
    threshold_for_angular_velocity: 0.01
    anti_windup_for_linear_velocity: 0.2
    anti_windup_for_angular_velocity: 0.7

/potential_function_node_2:
  ros__parameters:
    current_robot_id: 2
    current_robot_name: "tb_2_0"
    number_of_obstacles: 0
    radius_of_robots: 1.0
    radius_outer: 20.0
    limit_distance_for_robots: 5.0
    K_gain: 50.0
    Kp_v: 0.1
    Ki_v: 0.0
    Kd_v: 0.0
    Kp_w: 0.8
    Ki_w: 0.05
    Kd_w: 0.0
    threshold_for_linear_velocity: 0.1
    threshold_for_angular_velocity: 0.01
    anti_windup_for_linear_velocity: 0.2
    anti_windup_for_angular_velocity: 0.7

/potential_function_node_3:
  ros__parameters:
    current_robot_id: 3
    current_robot_name: "tb_3_0"
    number_of_obstacles: 0
    radius_of_robots: 1.0
    radius_outer: 20.0
    limit_distance_for_robots: 5.0
    K_gain: 50.0
    Kp_v: 0.1
    Ki_v: 0.0
    Kd_v: 0.0
    Kp_w: 0.8
    Ki_w: 0.05
    Kd_w: 0.0
    threshold_for_linear_velocity: 0.1
    threshold_for_angular_velocity: 0.01
    anti_windup_for_linear_velocity: 0.2
    anti_windup_for_angular_velocity: 0.7

/potential_function_node_4:
  ros__parameters:
    current_robot_id: 4
    current_robot_name: "tb_4_0"
    number_of_obstacles: 0
    radius_of_robots: 1.0
    radius_outer: 20.0
    limit_distance_for_robots: 5.0
    K_gain: 50.0
    Kp_v: 0.1
    Ki_v: 0.0
    Kd_v: 0.0
    Kp_w: 0.8
    Ki_w: 0.05
    Kd_w: 0.0
    threshold_for_linear_velocity: 0.1
    threshold_for_angular_velocity: 0.01
    anti_windup_for_linear_velocity: 0.2
    anti_windup_for_angular_velocity: 0.7