/potential_function_node:
  ros__parameters:
    current_robot_id: 0
    number_of_obstacles: 0
    radius_of_robots: 0.5
    radius_outer: 1000.0
    limit_distance_for_robots: 10.0
    K_gain: 10.0
    Kp_v: 0.1
    Ki_v: 0.05
    Kd_v: 0.05
    Kp_w: 0.1
    Ki_w: 0.05
    Kd_w: 0.05
