/target_pose_list_publisher_node:
  ros__parameters:
    tb_0_0: 
      x: -2.0
      y: -1.0

    tb_1_0:
      x: 0.0
      y: 0.0

    # tb_2_0:
    #   x: 21.0
    #   y: -10.0

    # tb_3_0:
    #   x: 3.0
    #   y: 6.0

    # tb_4_0:
    #   x: 15.0
    #   y: 15.0